### ISSUE TITLE
Where is the Log's file?

### ISSUE THREAD

**Issue by faultables** [Baisang/LearnCoin#1]
Hai, Baisang! I have some trouble when i success compiling the program. When I run the "Learncoin" daemon with: ./LearnCoin commands, the output is like what i hope:
./LearnCoin
LearnCoin: main.cpp:2047: bool LoadBlockIndex(bool): Assertion `block.hashMerkleRoot == uint256("0xef7e256a2cf2d38576225af2775a1e8160928a0c78526ab3615615d1ff16870e")' failed.
Aborted (core dumped)

But, i cannot find where the log's file is? When I run your command, 
$cd
$cd .LearnCoin
bash: cd: .LearnCoin: No such file or directory

Where the .LearnCoin's directory storaged is?
I use Lubuntu here. Thanks

**Comment by faultables** [comment]
Solved XD

**Comment by Baisang** [comment]
Where did you end up finding it? When I originally wrote this guide I was very very new to Linux, so that's why there are some pretty bad explanations of commands in it.

**Comment by faultables** [comment]
This problem is fixed, i was found it!
